version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Welcome
  keycloak:
    image: jboss/keycloak:4.0.0.Final
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_USER=postgres
      - DB_PASSWORD=Welcome
      - DB_ADDR=db
      - DB_PORT=5432
      - DB_DATABASE=postgres
    ports:
      - "8080:8080"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      username: postgres
      password: Welcome
      url: db:5432/postgres
    ports:
      - "8000:8000"
