version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  keycloak:
    image: jboss/keycloak:4.0.0.Final
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_PORT=5432
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_SCHEMA=public
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=./realm-export.json
      - KEYCLOAK_FRONTEND_URL=http://localhost:8080/auth
    ports:
      - "8080:8080"
    depends_on:
      - db

  gradle-continuous-builder:
    image: gradle:6.7.0-jdk11
    volumes:
      - gradle-build:/home/gradle/project/.gradle
      - ./:/home/gradle/project:cached
    working_dir: /home/gradle/project
    command: ["gradle","build","--continuous"]
    depends_on:
      - kafka
    links:
      - kafka:kafka

  gradle-execute:
    image: gradle:6.7.0-jdk11
    ports:
      - "8000:8000"
    environment:
      username: postgres
      password: Welcome
      url: db:5432/postgres
    volumes:
      - gradle-execution:/home/gradle/project/.gradle
      - ./:/home/gradle/project:cached
    working_dir: /home/gradle/project
    command: ["gradle","bootRun","-s"]
    depends_on:
      - kafka
    links:
      - kafka:kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./zoo/data:/var/lib/zookeeper/data
      - ./zoo/log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./logs/data:/var/lib/kafka/data

volumes:
  gradle-execution:
  gradle-build: