spring:
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: "my_group_id"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: kafka:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: Welcome
    hikari:
      connectionTimeout: 30000

app:
  version: 1.0.0

keycloak:
  realm: Covid-alert
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: springboot-microservice
  credentials:
    secret: 0444b510-8532-4a50-9eea-a031e53b5acb
  use-resource-role-mappings: true
  bearer-only: true

server:
  port: 8000
