spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: Welcome
    hikari:
      connectionTimeout: 30000

app:
  version: 1.0.0

keycloak:
  realm: Covid-alert
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: covid-alert
  credentials:
    secret: f3710609-b106-4c41-b1be-537cee5f84cf
  use-resource-role-mappings: true
  bearer-only: true
  verify-token-audience: true
  cors: true

server:
  port: 8000
